language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: 2AkwDTK3FUukH0xEd8hU5/+Zacw3RvwURH5sJCI2ulQercZ2xXi4+AyPepqdVXfCIC48Vg30TqSoDzkzNOjwYYAHVXr1dZEGt5xh9kfvSK2Afemo3s+LZqRB69RPpENPyLeqnQZHVC+zAZYwjwAUSWa9BoLJgFqD7V4lROlxvIBOBjYIpHJGVkT6bnsdh80PhOxM+C4UuI2ouJw9YMM5o1v/H1ib/9i/eWjC6HAp1YjrQesu0+WI3Kv2lEuwXcG4mCXMGoQO7NcZr94f4b9+a3lth5jquXsuLlFRjvIZnsFkYN+QBr3pzJEYWNACq4oIIQlhAeOMq5viVIfUcUxyzcP9TLEn7eM4lyDtgFSV6IqR0zuINU3g0CqjWomO0y2Jy66nnKiBJsfvEqfn/5zpaXMLI5lZx1vvv0S3VW6d5nacyuYYtifbmhQ5smIGoZsCIClZNQubqun7RPI5tH2QNBHQTYT9/gWcGaA4mVkdiHj5iCYpgEM595FLjW9MInNn0QWvSuksJyX4fHDBGBc2fZISiyzqP8CNwc1dVdLladiJlAnzk1YxAyvxpki2IAsxMKQJYa8bSMicHO7493CuyM6T7lOuqWkAUtp3VH+f7UfYTAY33IWRRcFDddaa73WVOePrMNlAY3FBxnaQWgsHBPnXvKIt+Q3EJTD2LFwXMkw=
jdk:
- openjdk8
sudo: false
script: mvn clean test install
after_success:
- mvn -Pdeploy deploy --settings travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
