---
name: build

on:
  push:
    branches: [main, "REL-*"]

  workflow_dispatch:
    inputs:
      skipTests:
        description: 'Skip tests'
        required: true
        default: 'false'

env:
  skipTests: false

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven
          server-id: vpro-ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
      - name: Build with Maven
        run: mvn -ntp -fae -DskipITs=false -DskipTests=${skipTests}  -U -B -Pdeploy,sonatype deploy  -Dgpg.skip=false
        env:
          SONATYPE_USERNAME: vpro
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Publish to codecov
        uses: codecov/codecov-action@v3
        continue-on-error: true
      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action/composite@v2.3.0
        with:
          junit_files: "**/target/surefire-reports/*.xml"
        if: always()
